workflows:
  android-workflow:
    name: Android Build with EAS
    max_build_duration: 120
    environment:
      node: 18.19.0
    triggering:
      events:
        - push
        - tag
    cache:
      cache_paths:
        - $HOME/.gradle/caches
        - $HOME/.gradle/wrapper
        - $HOME/Library/Caches/CocoaPods
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Setup EAS
        script: |
          npm install -g eas-cli
      - name: Build with EAS
        script: |
          eas build --platform android --non-interactive
    artifacts:
      - android/app/build/outputs/bundle/release/**/*.aab
