workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 120
    environment:
      node: 18.18.0
    triggering:
      events:
        - push
        - tag
    cache:
      cache_paths:
        - $HOME/Library/Caches/CocoaPods
        - $HOME/.gradle/caches
        - $HOME/.gradle/wrapper
    scripts:
      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps
      - name: Prebuild project
        script: |
          npx expo prebuild --clean
      - name: Build Android App Bundle
        script: |
          cd android
          ./gradlew bundleRelease
    artifacts:
      - android/app/build/outputs/bundle/release/**/*.aab
